### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by tsengvn** [kevinresol/react-native-default-preference#12]
I got this error when try to use the module, occurred on both android and ios

`undefined is not an object (evaluating '_reactNativeDefaultPreference2.default.get')`

Do you have any idea why ? 

Thanks so much.

**Comment by kevinresol** [comment]
No idea, everyone uses it fine

**Comment by dozel** [comment]
@tsengvn can you share how you're using the library?

**Comment by tsengvn** [comment]
@dozel I figured out the issue, i run my project by using expo

**Comment by aledalgrande** [comment]
you can also get this issue when you are trying to use this library in an app extension and you linked only to the main app, solution: follow the manual linking steps for the app extension target/project
