### ISSUE TITLE
RNDefaultPreferencePackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by fcostaprojects** [kevinresol/react-native-default-preference#16]
Hi, @kevinresol ,
after update to release 1.3.0, show error:
RNDefaultPreferencePackage is not abstract and does not override abstract method createJSModules() in ReactPackage.

Solution
missing the method:
  @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
      return Collections.emptyList();
    }

**Comment by kevinresol** [comment]
What is your RN version? Can you try v1.2.1 of this lib?

**Comment by fcostaprojects** [comment]
Hi @kevinresol, i'm using version => "react-native": "0.51.0".

**Comment by kevinresol** [comment]
Strange, https://github.com/kevinresol/react-native-default-preference/issues/15 says I should remove the method.

I don't have a working project now. Can you submit a PR that works?

**Comment by kevinresol** [comment]
ref: https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

**Comment by kevinresol** [comment]
Seems like I shouldn't remove the whole method but only the `@override` annotation. (https://github.com/realm/realm-js/issues/1176#issuecomment-319874290)

**Comment by kevinresol** [comment]
Please try `1.3.1`

**Comment by fcostaprojects** [comment]
I tried the version 1.3.1, issue fixed, thanks.
