### ISSUE TITLE
Android Error at react-native run-android: more than one library with package name 'com.reactlibrary'

### ISSUE THREAD

**Issue by Jesuskfc** [kevinresol/react-native-default-preference#19]
When i run react-native run-android give me the next error:

Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.reactlibrary'

I tried autoinstall and manual install

**Comment by kevinresol** [comment]
Probably need some fix like this one: https://github.com/kevinresol/react-native-sound-recorder/commit/134027346534a5d32da7f88a94df60455e62b1b8

**Comment by julianoabrs** [comment]
Any update on that? I'm having problems with that package name

**Comment by kevinresol** [comment]
PR welcome

**Comment by yamiscott** [comment]
Your PR works and looks good. Any idea when this will be accepted?
