### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNativeDefaultPreference2.default.get')

### ISSUE THREAD

**Issue by umakantp** [kevinresol/react-native-default-preference#20]
I get the following error, when I follow above steps in  react-native's boiler plate and try to run it.

TypeError: undefined is not an object (evaluating '_reactNativeDefaultPreference2.default.get')

**Comment by kevinresol** [comment]
Did you recompile the native app after including the library? e.g. `react-native run-ios`

**Comment by jay70077** [comment]
i did so many times but still i am getting error @kevinresol can u suggest some other way

**Comment by kevinresol** [comment]
Please follow the installation guide.

**Comment by jay70077** [comment]
@umakantp can you explain how u resolve this error??

**Comment by yazidIT** [comment]
@jay70077 you have to follow the instruction (similar to snapshot below). We call it "link" with native library.
![image](https://user-images.githubusercontent.com/37555972/47210749-09553600-d394-11e8-9f93-db88f1abcc4b.png)

**Comment by jay70077** [comment]
@yazidIT i did but still not able to run ..is there any react native version problem??

**Comment by yazidIT** [comment]
i am on RN ver 0.55.3

**Comment by philong9192** [comment]
YOU MUST "POD INSTALL" AFTER "LINK". 
I LOST SO MANY TIME TO FIND OUT THE SOLUTION. :((

**Comment by tannerhallman** [comment]
I am getting a null reference on:

`  "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-default-preference": "^1.4.3",`

```

import DefaultPreference from "react-native-default-preference";
....

useEffect(() => {
    //todo change this to dynamic
    if (DefaultPreference != null) {
      DefaultPreference.get("CURRENT_USER_DEV").then((value) => {
        console.log(value);
        setUser(value);
      });
    } else {
      console.log(DefaultPreference);
    }
  }, []);

```

rebuilt app, cleaned build files in android studio, restarted bundler, ran with android studio, ran with react-native run-android
