### ISSUE TITLE
getMultiple not working

### ISSUE THREAD

**Issue by rupalpatel0008** [kevinresol/react-native-default-preference#21]
I am trying to read four strings from preferences. 

Its giving me this error in android.
![device-2018-05-18-102213](https://user-images.githubusercontent.com/17310222/40216674-c1f9e634-5a85-11e8-9c9a-f6c6a3abf010.png)

react-native version: 0.54
react-native-default-preferences version: 1.3.1

This is the code I have written to get multiple data:
    ```
DefaultPreference.get(['MAJOR', 'MINOR', 'LATITUDE', 'LONGITUDE']).then((data) => {
      console.log('data = ', data);
    });
```

**Comment by kevinresol** [comment]
You need to use `getMultiple`
