### ISSUE TITLE
getAll and get cannot retrieve dictionaries from the UserDefaults

### ISSUE THREAD

**Issue by anish531213** [kevinresol/react-native-default-preference#23]
Hi, I wanted to retrieve the "com.apple.configuration.managed" from the UserDefaults but its not getting the dictionary. Can you give me any suggestion here?

**Comment by kevinresol** [comment]
maybe something like this? https://github.com/kevinresol/react-native-default-preference/pull/24

**Comment by kevinresol** [comment]
@anish531213 I wonder will you ever need to write back to the UserDefaults in form of a dictionary?

**Comment by kevinresol** [comment]
I have decided that the scope of this library is to handle string values only. So closing this one.
