### ISSUE TITLE
hard coded buildToolsVersion causing warning after upgrading to RN 0.57

### ISSUE THREAD

**Issue by codeword** [kevinresol/react-native-default-preference#27]
> Configure project :react-native-default-preference
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (25.0.3) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

**Comment by guix77** [comment]
It's fixed on master but there is no new release yet.
