### ISSUE TITLE
Update to 1.3.2 from 1.3.1 makes android release crash

### ISSUE THREAD

**Issue by angelos3lex** [kevinresol/react-native-default-preference#28]
If I update from 1.3.1 to v1.3.2 i get following error:

```
error: cannot find symbol
import com.reactlibrary.RNDefaultPreferencePackage;
                       ^
  symbol:   class RNDefaultPreferencePackage
  location: package com.reactlibrary
```

Wat's the change in new version?
RN version: 0.56

**Comment by kevinresol** [comment]
Package name changed to `com.kevinresol.react_native_default_preference`

See #26

**Comment by angelos3lex** [comment]
Still similar error in compileReleaseJavaWithJavac:
 ```
error: cannot find symbol
import com.kevinresol.react_native_default_preference;
```

**Comment by kevinresol** [comment]
`import com.kevinresol.react_native_default_preference.RNDefaultPreferencePackage;`
