### ISSUE TITLE
Add a change listener mechanism based on Keys

### ISSUE THREAD

**Issue by benzman81** [kevinresol/react-native-default-preference#29]
Currently I use the Settings API from react native. This supports a Methode watchKeys to listen to changes via NSUserDefaultsDidChangeNotification. Additionally I needed a wrapper to support change notifications via its set() method, as NSUserDefaultsDidChangeNotificationonly gets triggered as the NSUserDefaults gets changed from outside the app. Both is needed for a react native app to listen correctly to NSUserDefaults changes. Any chance you could implement this?

**Comment by kevinresol** [comment]
> Any chance you could implement this?

Sorry to say, but no.

And I think the functionality is out of scope of the library. As you have said already, this can be achieved by wrapping the `set()` function of this library and react native's Settings API into a single watch API and I think such wrapper deserves a separate library.

**Comment by beinginorbit** [comment]
@kevinresol one thing that this library does provide that the Settings API  that is baked in to RN doesn't is support suiteName (which is helpful when you have a today widget). Just a thought, I'm implementing this currently and will play around and report back if there's a workaround without watchKeys.
