### ISSUE TITLE
Print quotes cause builds to fail 

### ISSUE THREAD

**Issue by mspanc** [kevinresol/react-native-default-preference#31]
The file `ios/RNDefaultPreference.h` contains print quotes instead of regular ones causing builds to fail:

<img width="814" alt="zrzut ekranu 2018-11-22 o 14 01 04" src="https://user-images.githubusercontent.com/389651/48905585-3cdb2280-ee62-11e8-9387-eed8a9f9e1d9.png">

E.g. the code is

`#elif __has_include(“RCTBridgeModule.h”)`

but it should be

`#elif __has_include("RCTBridgeModule.h")`

**Comment by kevinresol** [comment]
Oh man, it must be from copy/paste. Could you contribute a PR for that?

**Comment by mspanc** [comment]
Sure, but a bit later
