### ISSUE TITLE
get from native code

### ISSUE THREAD

**Issue by patrickgodinho** [kevinresol/react-native-default-preference#39]
Hi, first, thanks for this lib.
Second, i need to get data from Siri Intent, that is not in react native project.

i have tried this:
React Native:
```await DefaultPreference.setName('group.myapp.test')```

Objective C
 ```
 NSUserDefaults *defaults = [[NSUserDefaults alloc] init];
   [defaults addSuiteNamed:@"group.myapp.test"];
  NSArray<NSString *> *defaultAsDic = [[defaults dictionaryRepresentation] allKeys];
```

But my custom keys arent in defaultAsDic.

Can someone help me please?

**Comment by kevinresol** [comment]
You sure the suite name is correct?

**Comment by patrickgodinho** [comment]
@kevinresol thanks for ur reply.
I already done my task, the group name was wrong. Actually i had not created the group and share with extensions. Btw, thanks!
