### ISSUE TITLE
Please remove peerDependencies

### ISSUE THREAD

**Issue by dozel** [kevinresol/react-native-default-preference#4]
https://twitter.com/notbrent/status/684107286994796544

It causes npm install to throw errors. I'm on react-native 0.37.

**Comment by dozel** [comment]
Nevermind, turns out my npm was out of date. The 'unmet depencency' warning is still there, but it installs the library just fine.

**Comment by dozel** [comment]
I'm re-opening this issue only because peerDependencies should be removed to get rid of the unmet dependency error.

**Comment by kevinresol** [comment]
I'm not particularly familiar with the dependency settings. So unless it doesn't work, I would like to keep it as is for now.

**Comment by dozel** [comment]
Cool, it still works as long as you update npm. NPM just complains about it, thankfully it's just a warning.
