### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by marcelkalveram** [kevinresol/react-native-default-preference#41]
Hi Kevin, this library is something I'm currently using in a client project, and was considering writing an extensions like this myself. 

I'd be happy to become a maintainer. Let me know if you're still looking for someone. Thanks!

**Comment by marcelkalveram** [comment]
Thanks for the invite @kevinresol. I'll probably look into updating the library in the next couple of weeks, as I'm using a similar solution in a project and would like to replace it with this one.

**Comment by marcelkalveram** [comment]
@kevinresol would it be possible to get npm access for this plugin, so I can release new versions of it?

**Comment by kevinresol** [comment]
give me your npm user name and I will add you there

**Comment by marcelkalveram** [comment]
Sure, it's `marcelkalveram`. Thanks!

**Comment by kevinresol** [comment]
ok, added
