### ISSUE TITLE
RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by JocelynAllard** [kevinresol/react-native-default-preference#52]
Hello!

When I try to build my project in XCode, I get an 'RCTBridgeModule.h not found' error message in RCTBridgeModule.h. I know it has something to do with the fact React.xcodeproj was removed in a previous react-native update, but I was wondering if there was a fix for that problem.

Thank you!

**Comment by marcelkalveram** [comment]
Hey @JocelynAllard can you tell me which version of RN you're on? Thanks!

**Comment by hamoudaarfaoui** [comment]
linking Via Cocoapods should solve the problem.
