### ISSUE TITLE
undefined reading from environment.plist on IOS

### ISSUE THREAD

**Issue by hamoudaarfaoui** [kevinresol/react-native-default-preference#55]
i linked the library via Cocoapods on RN0.61 and can't read properties it always return undefined, where should i place or read properties from ?

**Comment by kevinresol** [comment]
Is your property value a string? Are you reading from the correct UserDefault instance?

**Comment by hamoudaarfaoui** [comment]
Yes it's string, but how to verify if it's the correct instance ? project already existed and reading UserDefault using another library i just moved to this after upgrading RN61

**Comment by kevinresol** [comment]
There is the getName/setName api

**Comment by hamoudaarfaoui** [comment]
so it doesnt load from `environment.plist` file ?

**Comment by kevinresol** [comment]
There is no code written in this lib that reads that. Is that done automatically by default? I'm not sure.

**Comment by hienpham2102** [comment]
Hi, This issue solved? I also get 'undefine'.

my package.json:
RN: 0.61.5,
react-native-default-preference: ^1.4.3

**Comment by kevinresol** [comment]
I don't think it is an issue of this library when it comes to "environment.plist". But if you do think so, please provide more information. Closing for now.
