### ISSUE TITLE
Does not provide access to default preferences on Android

### ISSUE THREAD

**Issue by jschnurholmes** [kevinresol/react-native-default-preference#57]
react-native-default-preferences is creating its own preferences scope on Android called "react-native" instead of reading/writing **deafult** preferences as the name implies. This prevents reading and writing global preferences that other libraries interact with, such as an IAB privacy string for purposes such as CCPA and GDPR compliance.

**Comment by marcelkalveram** [comment]
@jschnurholmes have you tried the `setName` method, as outlines in the API docs:

```
/** Gets and sets the current preferences file name (android) or user default suite name (ios) **/
function setName(name:String):Promise<Void>;
```

**Comment by magrinj** [comment]
@jschnurholmes I've just made a PR about that here: https://github.com/kevinresol/react-native-default-preference/pull/62
You can actually use `setName` as @marcelkalveram reference with this pattern `YOUR_PACKAGE_NAME_preferences`, but as the iOS side is using the default one I think it's better if both sides iOS and Android are working the same.
