### ISSUE TITLE
sharing credentials across schemes

### ISSUE THREAD

**Issue by art1373** [kevinresol/react-native-default-preference#61]
is this library provide sharing a login state like a token or some user defaults across schemes

useCase I am considering:
App A : User logins with this app and assigned a jwt and close this app
APP B( with the same source but different scheme): user open this app and is automatically signed in

**Comment by kevinresol** [comment]
Generally speaking, UserDefault and SharedPreferences are sandboxed. Please refer to the official documentation for more details.
