### ISSUE TITLE
How to get and return value from a custom function

### ISSUE THREAD

**Issue by WeTruck** [kevinresol/react-native-default-preference#66]
I've a custom function like this,

```
export function getValueFromDevice(key) {
  key = key.toString();
  DefaultPreference.get(key).then(function (value) {
    console.log(value); //I'm getting value here
    return value;
  });
};
```

Calling the function,

```
import * as GeneralHelper from './../helpers/GeneralHelper';
const levelFromDevice = GeneralHelper.getValueFromDevice("level");
console.log(levelFromDevice) //It's showing undefined
```

Please help. 
Thanks in advance.

**Comment by kevinresol** [comment]
This is not really an issue of this library. You need to learn how to work with Promises.

**Comment by WeTruck** [comment]
@kevinresol Thanks. I can't get it done. Can you please show me how I can use it in this context or give me a reference?

**Comment by kevinresol** [comment]
Okay no problem. But now I guess you should start by learning how to google a topic. You can follow the following steps:

1. open www.google.com in your browser
2. type "js promise" in the text box and click on the "search" button

**Comment by WeTruck** [comment]
Thanks for your help. 😄
