### ISSUE TITLE
New npm release?

### ISSUE THREAD

**Issue by saghul** [kevinresol/react-native-default-preference#69]
Hey there! 👋

Thanks fore this package! We've been using it successfully with Jitsi Meet for quite a while now! I noticed we have our version pinned to a commit because we need the Xcode 12 fixes. Those are not currently on any release. Any chance you could make one?

**Comment by ilikeintegratedcircuit** [comment]
Hello
Great library, also really looking forward to npm release

**Comment by disko23** [comment]
Hey there! wave

Thanks fore this package! We've been using it successfully with Jitsi Meet for quite a while now! I noticed we have our version pinned to a commit because we need the Xcode 12 fixes. Those are not currently on any release. Any chance you could make one?

**Comment by kevinresol** [comment]
Sorry for the delay, just released as v1.4.4!

**Comment by ilikeintegratedcircuit** [comment]
Thank you
