### ISSUE TITLE
NullPointerException occurs when accessing sharedPreference from HeadlessJS on Android

### ISSUE THREAD

**Issue by mswokk** [kevinresol/react-native-default-preference#7]
HeadlessJS is designed to work in background without Activity on Android.

getReactApplicationContext() should be used to access Context instead of CurrentActivity

**Comment by kevinresol** [comment]
Can you try replacing [`getCurrentActivity()`](https://github.com/kevinresol/react-native-default-preference/blob/e8e7b7e/android/src/main/java/com/reactlibrary/RNDefaultPreferenceModule.java#L104) with the stored reference [`reactContext`](https://github.com/kevinresol/react-native-default-preference/blob/e8e7b7e/android/src/main/java/com/reactlibrary/RNDefaultPreferenceModule.java#L23) and file a PR if that works?

**Comment by mswokk** [comment]
I have confirmed it works.
What do you mean by 'file a PR' ? Could you explain it in more detail?

**Comment by kevinresol** [comment]
Oh, I mean to put up a pull request, so I can merge your code into this repo.
After that I will make a npm release.

**Comment by kevinresol** [comment]
Closed by #8

**Comment by mswokk** [comment]
Thank you for quick actions.
